# Generated by Django 3.1.1 on 2020-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('autor', models.CharField(max_length=12)),
            ],
        ),
    ]
